const TRANSLATIONS = {
    tr: {
        // --- Navigasyon ---
        "nav_char": "Karakter Sayfası",
        "nav_roller": "Zar Atıcı",
        "nav_find_campaign": "Kampanya Ara",
        "nav_campaign": "Kampanya Paneli (GM)",
        "nav_tools": "İçe / Dışa Aktar",
        "nav_gm_admin": "GM Yönetim",
        "nav_credits": "Emeği Geçenler", 
        
        // --- Karakter Kartı ---
        "card_char_info": "Karakter Bilgileri",
        "card_aspects": "Aspektler",
        "card_skills": "Beceriler",
        "card_stunts": "Yetenekler",
        "card_stress": "Stres & Sonuçlar",
        
        // --- Form Etiketleri ---
        "label_name": "İsim:",
        "label_desc": "Açıklama:",
        "label_refresh": "Refresh:",
        "label_fate_points": "Fate Puanı:",
        "label_high_concept": "High Concept:",
        "label_trouble": "Trouble:",
        "label_relationship": "Relationship:",
        "label_aspect1": "Serbest Aspekt 1:",
        "label_aspect2": "Serbest Aspekt 2:",
        
        // --- Stres & Sonuçlar ---
        "header_phys_stress": "Fiziksel Stres",
        "header_ment_stress": "Zihinsel Stres",
        "header_consequences": "Sonuçlar",
        "label_mild": "Hafif (Mild -2):",
        "label_mild_extra": "Ekstra Hafif (Mild -2):",
        "label_moderate": "Orta (Moderate -4):",
        "label_severe": "Şiddetli (Severe -6):",

        // --- Zar & Loglar ---
        "card_roller_title": "FATE ZAR ATICI",
        "card_roll_history": "Zar Geçmişi",
        "btn_roll": "ZAR AT",
        "label_roll_skill": "Beceri:",
        "log_roll_dice": "Zar",
        "log_roll_skill": "Beceri",
        "log_roll_total": "Toplam",
        "log_fate_spent": "Fate Puanı harcandı!",
        
        // --- Ladder (Zar Sonuçları) ---
        "ladder_8": "Efsanevi!",
        "ladder_7": "İnanılmaz!",
        "ladder_6": "Şahane!",
        "ladder_5": "Muhteşem!",
        "ladder_4": "Harika!",
        "ladder_3": "Güzel!",
        "ladder_2": "İyi!",
        "ladder_1": "Eh",
        "ladder_0": "Sıradan",
        "ladder_-1": "Zayıf",
        "ladder_-2": "Kötü",
        "ladder_-3": "Rezalet!",
        "ladder_-4": "Felaket!",

        // --- Beceriler ---
        "skill_academics": "Akademik",
        "skill_athletics": "Atletizm",
        "skill_burglary": "Hırsızlık",
        "skill_contacts": "Bağlantılar",
        "skill_crafts": "Zanaat",
        "skill_deceive": "Aldatmaca",
        "skill_drive": "Sürüş",
        "skill_empathy": "Empati",
        "skill_fight": "Dövüş",
        "skill_investigate": "Araştırma",
        "skill_lore": "Bilgi",
        "skill_notice": "Farkındalık",
        "skill_physique": "Beden",
        "skill_provoke": "Kışkırtma",
        "skill_rapport": "Muhabbet",
        "skill_resources": "Kaynaklar",
        "skill_shoot": "Atıcılık",
        "skill_stealth": "Gizlilik",
        "skill_will": "İrade",

        // --- Emeği Geçenler (Credits) ---
        "credits_title": "Emeği Geçenler",
        "credits_dev": "Geliştirici & Kodlama",
        "credits_design": "Tasarım & Fikirler",
        "credits_translation": "Çeviri Ekibi",

        // --- Genel Butonlar ve Mesajlar ---
        "btn_add": "Ekle",
        "btn_delete": "Sil",
        "btn_cancel": "İptal",
        "btn_confirm": "Onayla",
        "btn_ok": "Tamam",
        "btn_close": "Kapat",
        "btn_submit_char": "Karakterimi Gönder",
        "btn_manage": "Yönet",
        "btn_update_campaign": "Kampanya Bilgilerini Güncelle",
        "btn_create_campaign": "Kampanyayı Lobiye Ekle",
        "btn_export": "Karakteri Dışa Aktar (Export)",
        "btn_import": "Karakteri İçe Aktar (Import)",
        "btn_reset": "Karakteri Sıfırla",
        "btn_leave_campaign": "Oyundan Ayrıl",
        "btn_add_result": "SONUCA +2 EKLE",
        "btn_reroll": "YENİDEN AT",
        
        // --- Durum Bildirimleri ---
        "btn_creating": "Oluşturuluyor...",
        "btn_updating": "Güncelleniyor...",
        
        // --- Kampanya ---
        "card_public_campaigns": "Genel Kampanyalar",
        "desc_public_campaigns": "Mevcut oyunları arayın ve karakterinizi gönderin. Bir GM iseniz, 'Yönet' butonuna basıp şifrenizi girin.",
        "card_new_campaign": "Yeni Kampanya Oluştur (GM)",
        "desc_new_campaign": "Oyuncuların lobi ekranında göreceği bilgileri doldurun.",
        "label_camp_name": "Oyun Adı:",
        "label_camp_gm": "GM Adı:",
        "label_camp_system": "Sistem:",
        "label_camp_setting": "Setting / Dünya:",
        "label_camp_players": "Kişi Sayısı:",
        "label_camp_desc": "Hikaye Kancası:",
        "label_camp_lore": "Detaylar / Lore (Opsiyonel):",
        "label_camp_password": "Yönetim Şifresi:",
        
        "card_gm_admin": "Kampanya Yönetimi",
        "desc_gm_admin": "Bu sayfayı sadece kampanya GM'i görebilir.",
        "card_situation_aspects": "Durum Aspektleri",
        "card_gm_fate": "GM Fate Puanı",
        "label_current_points": "Güncel Puan:",
        "card_submitted_chars": "Başvuran Karakterler",
        "card_approved_players": "Onaylanmış Oyuncular",
        "card_danger_zone": "Tehlikeli Bölge",
        "desc_danger_zone_camp": "Bu işlem geri alınamaz. Kampanyayı, içindeki tüm oyuncuları ve başvuruları kalıcı olarak siler.",
        "btn_delete_campaign": "Kampanyayı Kalıcı Olarak Sil",
        
        // --- Import / Export ---
        "card_char_data": "Karakter Verisi",
        "desc_char_data": "Karakterinizi bir .json dosyası olarak kaydedebilir veya daha önce kaydettiğiniz bir dosyayı yükleyebilirsiniz. Bu, karakterinizi paylaşmanın en iyi yoludur.",
        "desc_danger_zone_char": "Bu işlem geri alınamaz. Mevcut karakterinizdeki tüm verileri (aspektler, beceriler, stunt'lar) sıfırlar.",

        "msg_saved": "Kaydedildi!",
        
        // --- Placeholder (Silik Yazılar) ---
        "placeholder_stunt": "Yeni Stunt açıklaması...",
        "placeholder_char_desc": "Karakterinizin kısa tanımı...",
        "placeholder_camp_name": "Örn: 'Kayıp Kader Kristali'",
        "placeholder_camp_gm": "Görünmesini istediğiniz isim...",
        "placeholder_camp_setting": "Örn: 'Ev Yapımı Fantastik, Cyberpunk'",
        "placeholder_camp_desc": "Oyuncular için kısa bir macera kancası...",
        "placeholder_camp_lore": "Ev kuralları, önemli NPC'ler, dünya bilgisi...",
        "placeholder_camp_password": "Unutmayacağınız bir şifre girin",
        "placeholder_gm_aspect": "Yeni durum aspekti...",
        "placeholder_high_concept": "Örn: 'Sihir Güçlü Kılıç Ustası'",
        "placeholder_trouble": "Örn: 'Altına Olan Zafiyeti'",
        "placeholder_relationship": "Örn: 'Eski Ustama Borçluyum'",
        "placeholder_aspect": "Serbest aspektiniz...",
        
        "card_live_aspects": "Canlı Durum Aspektleri (GM)",

        // === MODAL MESAJLARI (EKSİKSİZ) ===
        "msg_error": "Hata",
        "msg_success": "Başarılı",
        "msg_warning": "Uyarı",
        "msg_confirmation": "Onay",
        "msg_operation_blocked": "İşlem Engellendi",
        "msg_connection_error": "Bağlantı Hatası",
        "msg_limit_exceeded": "Limit Aşıldı",
        "msg_rule_violation": "Kural İhlali",
        "msg_login_error": "Giriş Hatası",
        "msg_capacity_full": "Kapasite Dolu",
        
        "txt_blocked_live": "Bir kampanyaya bağlıyken bu işlemi yapamazsınız. Lütfen önce oyundan ayrılın.",
        "txt_last_char_warning": "Bu son karakteriniz. Son karakteri silemezsiniz. (Bunun yerine 'Karakteri Sıfırla' butonunu kullanın.)",
        "txt_delete_char_confirm": "{name} adlı karakteri kalıcı olarak silmek istediğinizden emin misiniz?",
        "txt_reset_char_confirm": "{name} adlı karakterin tüm verilerini sıfırlamak istediğinizden emin misiniz?",
        "txt_stunt_limit": "Stunt limitine ulaştınız. Refresh puanınızı düşürmelisiniz.",
        "txt_refresh_limit": "Refresh'i {value} değerine düşüremezsiniz. Önce Stunt silmelisiniz.",
        "txt_skill_pyramid": "Sadece {limit} adet '+{value}' beceriye sahip olabilirsiniz.",
        "txt_fate_point_limit": "Harcanacak Fate Puanın yok!",
        "txt_import_success": "Karakter başarıyla içe aktarıldı.",
        "txt_import_overwrite": "{new} karakterini yüklüyorsunuz.\n'Onayla': {current} üzerine yaz.\n'İptal': Yeni olarak ekle.",
        "txt_char_updated": "Karakter başarıyla güncellendi.",
        "txt_char_added": "Karakter başarıyla listeye eklendi.",
        "txt_invalid_file": "Geçersiz karakter dosyası.",
        "txt_leave_game_confirm": "Şu an bağlı olduğunuz oyundan ayrılmak istediğinize emin misiniz?",
        "txt_leave_success": "Oyundan başarıyla ayrıldınız.",
        "txt_gm_password_prompt": "Bu kampanyayı yönetmek için şifrenizi girin:",
        "txt_password_wrong": "Şifre yanlış!",
        "txt_campaign_created": "Kampanyanız lobiye eklendi.",
        "txt_campaign_updated": "Kampanya güncellendi.",
        "txt_missing_info": "Lütfen gerekli alanları doldurun.",
        "txt_delete_campaign_confirm": "Bu kampanyayı kalıcı olarak silmek istediğinizden emin misiniz?",
        "txt_delete_campaign_prompt": "Silmek için kampanya adını yazın: '{name}'",
        "txt_name_mismatch": "Girilen isim eşleşmedi.",
        "txt_campaign_deleted": "Kampanya silindi.",
        "txt_kick_confirm": "{name} adlı oyuncuyu oyundan atmak istediğinizden emin misiniz?",
        "txt_kicked": "{name} oyundan atıldı.",
        "txt_approve_confirm": "{name} adlı karakteri oyuna onaylamak istiyor musunuz?",
        "txt_approved": "{name} oyuna onaylandı!",
        "txt_deny_confirm": "{name} başvurusunu reddetmek istiyor musunuz?",
        "txt_submit_missing": "Lütfen İsim ve High Concept alanlarını doldurun.",
        "txt_submit_confirm": "{name} karakterini '{campaign}' oyununa göndermek istiyor musunuz?",
        "txt_submitted": "Başvuru alındı!",
        "txt_live_connection_lost": "Oyuna olan canlı bağlantı koptu.",
        "txt_application_status": "Başvurunuz reddedildi veya oyundan çıkarıldınız.",
        "txt_player_count_error": "Kişi sayısı 1-10 arasında olmalı.",
        "txt_firebase_error": "Veritabanı (Firebase) hatası oluştu.",
        
        // --- Durum Çubuğu Mesajları ---
        "txt_status_live": "CANLI MOD: \"{campaign}\" oyununa bağlısınız.",
        "txt_status_pending": "ONAY BEKLENİYOR: \"{campaign}\" oyunu için başvurunuz alındı.",
        // lang.js İÇİNDEKİ 'tr' BÖLÜMÜNE EKLE:
        "txt_fate_gt_refresh": "Fate Puanı, Refresh değerinden yüksek olamaz.",
        "label_limit": "Limit:",
        "label_used": "Kullanılan:",
        "txt_empty_stunt": "(Boş)",
        // TR Bölümü içine:
"lbl_fate_cost": "-1 Fate Puanı",
// TR Bölümü:
"txt_unnamed_char": "İsimsiz Karakter",
"txt_char_deleted_success": "Karakter başarıyla silindi.",
        "txt_char_reset_success": "Aktif karakter başarıyla sıfırlandı.",
        "title_notes": "Kişisel Notlar",
        "placeholder_notes": "Buraya macera notlarını alabilirsin...",
        "txt_notes_saved": "Kaydedildi",
        "btn_notes_toggle": "Notlar",
        "label_camp_skills": "Kampanya Becerileri:",
        "desc_camp_skills": "İstemediklerinizi (X) ile çıkarın, aşağıdan yeni ekleyin.",
        "placeholder_add_skill": "Yeni beceri adı...",
        "btn_reset_skills": "Varsayılan Listeye Dön",
        "msg_duplicate_skill": "Bu beceri zaten listede var!",
        "btn_game_mode": "🎮 Oyun Modu",
        "btn_edit_mode": "✏️ Düzenleme Modu",
        "lbl_game_mode_active": "Oyun Modu Aktif",
        // --- Rehber / Guide ---
        "nav_guide": "Nasıl Kullanılır?",
        "guide_title": "Hoş Geldiniz & Kullanım Kılavuzu",
        "guide_welcome": "FATE RPG Karakter Kağıdı uygulamasına hoş geldiniz! Bu araç, oyunlarınızı hızlandırmak ve kolaylaştırmak için tasarlandı.",
        "guide_feat_1": "Karakter Yaratma & Düzenleme",
        "guide_feat_2": "Zar Atıcı (Dice Roller)",
        "guide_feat_3": "Kampanya Oluşturma & Beceri Özelleştirme (GM)",
        "guide_feat_4": "Kampanyalara Katılma (Canlı Oyun)",
        "guide_warn_backup": "Sistem geliştirme aşamasındadır (BETA). Verilerinizi kaybetmemek için Araçlar menüsünden 'Dışa Aktar' (Export) yaparak düzenli yedek almanız önerilir.",
        "guide_warn_bugs": "Hata bulursanız veya öneriniz varsa, menüdeki sosyal medya ikonlarından (Discord/Reddit) geliştiriciye ulaşabilirsiniz.",
        "guide_step_skill_title": "Becerileri Kontrol Edin",
        "guide_step_skill_desc": "Karakterinizi yaratıp bir Kampanyaya bağlandıktan sonra mutlaka 'Beceriler' sekmesini kontrol edin. GM, kampanya için özel beceriler eklemiş veya çıkarmış olabilir. Bağlantı koptuğunda beceriler normale döner, tekrar bağlandığınızda kampanya ayarları geri gelir.",
        "guide_step_multi_title": "Çoklu Karakter & Temiz Oyun",
        "guide_step_multi_desc": "Birden fazla karakteriniz varsa; sadece oyun gecesi, ilgili karakterle kampanyaya bağlanın. Oyun bitiminde mutlaka 'Oyundan Ayrıl' butonunu kullanın, sonra diğer karaktere geçin. Bu, veri karışıklığını önler.",
        "guide_step_mode_title": "Oyun Modu & Zar Atıcı",
        "guide_step_mode_desc": "Önce Kampanyaya bağlanın, sonra 'Oyun Modu' (Gamepad İkonu) butonuna basın. Zarları görmek için menüden 'Zar Atıcı' sekmesine tıklarsanız, zar paneli karakter kağıdının altına otomatik yerleşir.",
        "btn_got_it": "Okudum, Anladım",
        // --- Rehber Başlıkları (EKSİKLER EKLENDİ) ---
        "guide_header_features": "🌟 Temel Özellikler",
        "guide_header_warnings": "⚠️ Önemli Uyarılar",
        "guide_header_steps": "🚀 Nasıl Oynanır? (Kritik Adımlar)",
        // (btn_got_it zaten vardı, yoksa ekle)
        "btn_got_it": "Okudum, Anladım",
    },
    
    en: {
        // --- Navigation ---
        "nav_char": "Character Sheet",
        "nav_roller": "Dice Roller",
        "nav_find_campaign": "Find Campaign",
        "nav_campaign": "Campaign Panel (GM)",
        "nav_tools": "Import / Export",
        "nav_gm_admin": "GM Admin",
        "nav_credits": "Credits",

        // --- Card Headers ---
        "card_char_info": "Character Info",
        "card_aspects": "Aspects",
        "card_skills": "Skills",
        "card_stunts": "Stunts",
        "card_stress": "Stress & Consequences",
        
        // --- Labels ---
        "label_name": "Name:",
        "label_desc": "Description:",
        "label_refresh": "Refresh:",
        "label_fate_points": "Fate Points:",
        "label_high_concept": "High Concept:",
        "label_trouble": "Trouble:",
        "label_relationship": "Relationship:",
        "label_aspect1": "Free Aspect 1:",
        "label_aspect2": "Free Aspect 2:",
        
        // --- Stress ---
        "header_phys_stress": "Physical Stress",
        "header_ment_stress": "Mental Stress",
        "header_consequences": "Consequences",
        "label_mild": "Mild (-2):",
        "label_mild_extra": "Extra Mild (-2):",
        "label_moderate": "Moderate (-4):",
        "label_severe": "Severe (-6):",

        // --- Roller ---
        "card_roller_title": "FATE DICE ROLLER",
        "card_roll_history": "Roll History",
        "btn_roll": "ROLL DICE",
        "label_roll_skill": "Skill:",
        "log_roll_dice": "Dice",
        "log_roll_skill": "Skill",
        "log_roll_total": "Total",
        "log_fate_spent": "Fate Point spent!",
        
        // --- Ladder ---
        "ladder_8": "Legendary!",
        "ladder_7": "Epic!",
        "ladder_6": "Fantastic!",
        "ladder_5": "Superb!",
        "ladder_4": "Great!",
        "ladder_3": "Good!",
        "ladder_2": "Fair!",
        "ladder_1": "Average",
        "ladder_0": "Mediocre",
        "ladder_-1": "Poor",
        "ladder_-2": "Terrible",
        "ladder_-3": "Abysmal!",
        "ladder_-4": "Catastrophic!",

        // --- Skills ---
        "skill_academics": "Academics",
        "skill_athletics": "Athletics",
        "skill_burglary": "Burglary",
        "skill_contacts": "Contacts",
        "skill_crafts": "Crafts",
        "skill_deceive": "Deceive",
        "skill_drive": "Drive",
        "skill_empathy": "Empathy",
        "skill_fight": "Fight",
        "skill_investigate": "Investigate",
        "skill_lore": "Lore",
        "skill_notice": "Notice",
        "skill_physique": "Physique",
        "skill_provoke": "Provoke",
        "skill_rapport": "Rapport",
        "skill_resources": "Resources",
        "skill_shoot": "Shoot",
        "skill_stealth": "Stealth",
        "skill_will": "Will",

        // --- Credits ---
        "credits_title": "Credits",
        "credits_dev": "Developer & Coding",
        "credits_design": "Design & Ideas",
        "credits_translation": "Translation Team",

        // --- General ---
        "btn_add": "Add",
        "btn_delete": "Delete",
        "btn_cancel": "Cancel",
        "btn_confirm": "Confirm",
        "btn_ok": "OK",
        "btn_close": "Close",
        "btn_submit_char": "Submit Character",
        "btn_manage": "Manage",
        "btn_update_campaign": "Update Campaign Info",
        "btn_create_campaign": "Create Campaign",
        "btn_export": "Export Character",
        "btn_import": "Import Character",
        "btn_reset": "Reset Character",
        "btn_leave_campaign": "Leave Campaign",
        "btn_add_result": "ADD +2 TO RESULT",
        "btn_reroll": "REROLL",
        
        // --- Status Buttons ---
        "btn_creating": "Creating...",
        "btn_updating": "Updating...",
        
        // --- Campaign ---
        "card_public_campaigns": "Public Campaigns",
        "desc_public_campaigns": "Search for existing games and submit your character. If you are a GM, click 'Manage' and enter your password.",
        "card_new_campaign": "Create New Campaign (GM)",
        "desc_new_campaign": "Fill in the information players will see in the lobby.",
        "label_camp_name": "Game Name:",
        "label_camp_gm": "GM Name:",
        "label_camp_system": "System:",
        "label_camp_setting": "Setting / World:",
        "label_camp_players": "Max Players:",
        "label_camp_desc": "Story Hook:",
        "label_camp_lore": "Details / Lore (Optional):",
        "label_camp_password": "Admin Password:",
        
        "card_gm_admin": "Campaign Management",
        "desc_gm_admin": "Only the campaign GM can see this page.",
        "card_situation_aspects": "Situation Aspects",
        "card_gm_fate": "GM Fate Points",
        "label_current_points": "Current Points:",
        "card_submitted_chars": "Submitted Characters",
        "card_approved_players": "Approved Players",
        "card_danger_zone": "Danger Zone",
        "desc_danger_zone_camp": "This action cannot be undone. Permanently deletes the campaign, all players, and submissions within it.",
        "btn_delete_campaign": "Permanently Delete Campaign",
        
        // --- Import / Export ---
        "card_char_data": "Character Data",
        "desc_char_data": "You can save your character as a .json file or load a previously saved file. This is the best way to share your character.",
        "desc_danger_zone_char": "This action cannot be undone. Resets all data (aspects, skills, stunts) in your current character.",

        "msg_saved": "Saved!",
        
        // --- Placeholders ---
        "placeholder_stunt": "New Stunt description...",
        "placeholder_char_desc": "Short description of your character...",
        "placeholder_camp_name": "e.g., 'The Lost Fate Crystal'",
        "placeholder_camp_gm": "Name you want to display...",
        "placeholder_camp_setting": "e.g., 'Homebrew Fantasy, Cyberpunk'",
        "placeholder_camp_desc": "A short adventure hook for players...",
        "placeholder_camp_lore": "House rules, important NPCs, world info...",
        "placeholder_camp_password": "Enter a password you won't forget",
        "placeholder_gm_aspect": "New situation aspect...",
        "placeholder_high_concept": "e.g., 'Wizard Private Eye'",
        "placeholder_trouble": "e.g., 'Sucker for a Pretty Face'",
        "placeholder_relationship": "e.g., 'I owe my old master'",
        "placeholder_aspect": "Your free aspect...",
        
        "card_live_aspects": "Live Situation Aspects (GM)",

        // === NEW: MODAL MESSAGES ===
        "msg_error": "Error",
        "msg_success": "Success",
        "msg_warning": "Warning",
        "msg_confirmation": "Confirmation",
        "msg_operation_blocked": "Operation Blocked",
        "msg_connection_error": "Connection Error",
        "msg_limit_exceeded": "Limit Exceeded",
        "msg_rule_violation": "Rule Violation",
        "msg_login_error": "Login Error",
        "msg_capacity_full": "Capacity Full",
        
        "txt_blocked_live": "You cannot perform this action while connected to a campaign. Please leave the game first.",
        "txt_last_char_warning": "This is your last character. You cannot delete the last character. (Use 'Reset Character' instead.)",
        "txt_delete_char_confirm": "Are you sure you want to permanently delete {name}?",
        "txt_reset_char_confirm": "Are you sure you want to reset all data for {name}?",
        "txt_stunt_limit": "Stunt limit reached. You must lower your Refresh.",
        "txt_refresh_limit": "You cannot lower Refresh to {value}. Delete stunts first.",
        "txt_skill_pyramid": "You can only have {limit} skill(s) at +{value}.",
        "txt_fate_point_limit": "You have no Fate Points to spend!",
        "txt_import_success": "Character imported successfully.",
        "txt_import_overwrite": "Loading {new}.\n'Confirm': Overwrite {current}.\n'Cancel': Add as new.",
        "txt_char_updated": "Character successfully updated.",
        "txt_char_added": "Character successfully added to list.",
        "txt_invalid_file": "Invalid character file.",
        "txt_leave_game_confirm": "Are you sure you want to leave the current game?",
        "txt_leave_success": "You have left the game.",
        "txt_gm_password_prompt": "Enter password to manage this campaign:",
        "txt_password_wrong": "Wrong password!",
        "txt_campaign_created": "Campaign added to the lobby.",
        "txt_campaign_updated": "Campaign updated.",
        "txt_missing_info": "Please fill in the required fields.",
        "txt_delete_campaign_confirm": "Are you sure you want to permanently delete this campaign?",
        "txt_delete_campaign_prompt": "Type campaign name to delete: '{name}'",
        "txt_name_mismatch": "Name mismatch.",
        "txt_campaign_deleted": "Campaign deleted.",
        "txt_kick_confirm": "Are you sure you want to kick {name}?",
        "txt_kicked": "{name} has been kicked.",
        "txt_approve_confirm": "Do you want to approve {name}?",
        "txt_approved": "{name} approved!",
        "txt_deny_confirm": "Do you want to deny the application for {name}?",
        "txt_submit_missing": "Please fill in Name and High Concept.",
        "txt_submit_confirm": "Do you want to submit {name} to '{campaign}'?",
        "txt_submitted": "Application submitted!",
        "txt_live_connection_lost": "Live connection to the game was lost.",
        "txt_application_status": "Your application was denied or you were kicked.",
        "txt_player_count_error": "Player count must be between 1 and 10.",
        "txt_firebase_error": "Database (Firebase) error occurred.",

        // --- Status Messages ---
        "txt_status_live": "LIVE MODE: Connected to \"{campaign}\".",
        "txt_status_pending": "APPROVAL PENDING: Application sent for \"{campaign}\".",
        // lang.js İÇİNDEKİ 'en' BÖLÜMÜNE EKLE:
        "txt_fate_gt_refresh": "Fate Points cannot exceed Refresh value.",
        "label_limit": "Limit:",
        "label_used": "Used:",
        "txt_empty_stunt": "(Empty)",
        // EN Bölümü içine:
"lbl_fate_cost": "-1 Fate Point",
// EN Bölümü:
"txt_unnamed_char": "Unnamed Character",
"txt_char_deleted_success": "Character deleted successfully.",
        "txt_char_reset_success": "Active character reset successfully.",
        "title_notes": "Personal Notes",
        "placeholder_notes": "Take notes for your adventure here...",
        "txt_notes_saved": "Saved",
        "btn_notes_toggle": "Notes",
        "label_camp_skills": "Campaign Skills:",
        "desc_camp_skills": "Remove unwanted skills with (X), add new ones below.",
        "placeholder_add_skill": "New skill name...",
        "btn_reset_skills": "Reset to Default List",
        "msg_duplicate_skill": "This skill is already in the list!",
        "btn_game_mode": "🎮 Game Mode",
        "btn_edit_mode": "✏️ Edit Mode",
        "lbl_game_mode_active": "Game Mode Active",
        // --- Guide ---
        "nav_guide": "How to Use?",
        "guide_title": "Welcome & User Guide",
        "guide_welcome": "Welcome to the FATE RPG Character Sheet app! This tool is designed to speed up and simplify your games.",
        "guide_feat_1": "Character Creation & Editing",
        "guide_feat_2": "Dice Roller",
        "guide_feat_3": "Campaign Creation & Custom Skills (GM)",
        "guide_feat_4": "Joining Campaigns (Live Play)",
        "guide_warn_backup": "System is in development (BETA). It is recommended to take regular backups using 'Export' from the Tools menu to avoid data loss.",
        "guide_warn_bugs": "If you find bugs or have suggestions, you can reach the developer via the social media icons (Discord/Reddit) in the menu.",
        "guide_step_skill_title": "Check Skills",
        "guide_step_skill_desc": "After joining a Campaign, always check the 'Skills' tab. The GM may have added or removed custom skills. Skills revert to normal when disconnected and return when reconnected.",
        "guide_step_multi_title": "Multi-Character & Clean Play",
        "guide_step_multi_desc": "If you have multiple characters; connect to the campaign only on game night with the relevant character. Always use the 'Leave Campaign' button when the game ends, then switch characters. This prevents data mix-ups.",
        "guide_step_mode_title": "Game Mode & Dice Roller",
        "guide_step_mode_desc": "First Connect to Campaign, then toggle 'Game Mode' (Gamepad Icon). To see dice, click the 'Dice Roller' tab from the menu; it will dock automatically below the character sheet.",
        "btn_got_it": "Read & Understood",
        // --- Guide Headers (ADDED) ---
        "guide_header_features": "🌟 Basic Features",
        "guide_header_warnings": "⚠️ Important Warnings",
        "guide_header_steps": "🚀 How to Play? (Critical Steps)",
        // (btn_got_it zaten vardı, yoksa ekle)
        "btn_got_it": "Read & Understood",
    }
};