const TRANSLATIONS = {
    tr: {
        // --- Navigasyon ---
        "nav_char": "Karakter Sayfası",
        "nav_roller": "Zar Atıcı",
        "nav_find_campaign": "Kampanya Ara",
        "nav_campaign": "Kampanya Paneli (GM)",
        "nav_tools": "İçe / Dışa Aktar",
        "nav_gm_admin": "GM Yönetim",
        "nav_credits": "Emeği Geçenler", 
        
        // --- Karakter Kartı ---
        "card_char_info": "Karakter Bilgileri",
        "card_aspects": "Aspektler (Aspects)",
        "card_skills": "Beceriler (Skills)",
        "card_stunts": "Yetenekler (Stunts)",
        "card_stress": "Stres & Sonuçlar",
        
        // --- Form Etiketleri ---
        "label_name": "İsim:",
        "label_desc": "Açıklama:",
        "label_refresh": "Refresh:",
        "label_fate_points": "Fate Puanı:",
        "label_high_concept": "High Concept:",
        "label_trouble": "Trouble:",
        "label_relationship": "Relationship:",
        "label_aspect1": "Serbest Aspekt 1:",
        "label_aspect2": "Serbest Aspekt 2:",
        
        // --- Stres & Sonuçlar ---
        "header_phys_stress": "Fiziksel Stres",
        "header_ment_stress": "Zihinsel Stres",
        "header_consequences": "Sonuçlar",
        "label_mild": "Hafif (Mild -2):",
        "label_mild_extra": "Ekstra Hafif (Mild -2):",
        "label_moderate": "Orta (Moderate -4):",
        "label_severe": "Şiddetli (Severe -6):",

        // --- Zar & Loglar ---
        "card_roller_title": "FATE ZAR ATICI",
        "card_roll_history": "Zar Geçmişi",
        "btn_roll": "ZAR AT",
        "label_roll_skill": "Beceri:",
        "log_roll_dice": "Zar",
        "log_roll_skill": "Beceri",
        "log_roll_total": "Toplam",
        "log_fate_spent": "Fate Puanı harcandı!",
        
        // --- Ladder (Zar Sonuçları) ---
        "ladder_8": "Efsanevi!",
        "ladder_7": "İnanılmaz!",
        "ladder_6": "Şahane!",
        "ladder_5": "Muhteşem!",
        "ladder_4": "Harika!",
        "ladder_3": "Güzel!",
        "ladder_2": "İyi!",
        "ladder_1": "Eh",
        "ladder_0": "Sıradan",
        "ladder_-1": "Zayıf",
        "ladder_-2": "Kötü",
        "ladder_-3": "Rezalet!",
        "ladder_-4": "Felaket!",

        // --- Beceriler ---
        "skill_academics": "Akademik",
        "skill_athletics": "Atletizm",
        "skill_burglary": "Hırsızlık",
        "skill_contacts": "Bağlantılar",
        "skill_crafts": "Zanaat",
        "skill_deceive": "Kandırma",
        "skill_drive": "Sürüş",
        "skill_empathy": "Empati",
        "skill_fight": "Dövüş",
        "skill_investigate": "Araştırma",
        "skill_lore": "Bilgi",
        "skill_notice": "Farkındalık",
        "skill_physique": "Bünye",
        "skill_provoke": "Kışkırtma",
        "skill_rapport": "İletişim",
        "skill_resources": "Kaynaklar",
        "skill_shoot": "Ateş Etme",
        "skill_stealth": "Gizlilik",
        "skill_will": "İrade",

        // --- Emeği Geçenler (Credits) ---
        "credits_title": "Emeği Geçenler",
        "credits_dev": "Geliştirici & Kodlama",
        "credits_design": "Tasarım & Fikirler",
        "credits_translation": "Çeviri Ekibi",

        // --- Genel Butonlar ve Mesajlar ---
        "btn_add": "Ekle",
        "btn_delete": "Sil",
        "btn_cancel": "İptal",
        "btn_confirm": "Onayla",
        "btn_ok": "Tamam",
        "btn_close": "Kapat",
        "btn_submit_char": "Karakterimi Gönder",
        "btn_manage": "Yönet",
        "btn_update_campaign": "Kampanya Bilgilerini Güncelle",
        "btn_create_campaign": "Kampanyayı Lobiye Ekle",
        "btn_export": "Karakteri Dışa Aktar (Export)",
        "btn_import": "Karakteri İçe Aktar (Import)",
        "btn_reset": "Karakteri Sıfırla",
        "btn_leave_campaign": "Oyundan Ayrıl",
        "btn_add_result": "SONUCA +2 EKLE",
        "btn_reroll": "YENİDEN AT",
        
        // --- Durum Bildirimleri ---
        "btn_creating": "Oluşturuluyor...",
        "btn_updating": "Güncelleniyor...",
        
        // --- Kampanya ---
        "card_public_campaigns": "Genel Kampanyalar",
        "desc_public_campaigns": "Mevcut oyunları arayın ve karakterinizi gönderin. Bir GM iseniz, 'Yönet' butonuna basıp şifrenizi girin.",
        "card_new_campaign": "Yeni Kampanya Oluştur (GM)",
        "desc_new_campaign": "Oyuncuların lobi ekranında göreceği bilgileri doldurun.",
        "label_camp_name": "Oyun Adı:",
        "label_camp_gm": "GM Adı:",
        "label_camp_system": "Sistem:",
        "label_camp_setting": "Setting / Dünya:",
        "label_camp_players": "Kişi Sayısı:",
        "label_camp_desc": "Hikaye Kancası:",
        "label_camp_lore": "Detaylar / Lore (Opsiyonel):",
        "label_camp_password": "Yönetim Şifresi:",
        
        "card_gm_admin": "Kampanya Yönetimi",
        "desc_gm_admin": "Bu sayfayı sadece kampanya GM'i görebilir.",
        "card_situation_aspects": "Durum Aspektleri",
        "card_gm_fate": "GM Fate Puanı",
        "label_current_points": "Güncel Puan:",
        "card_submitted_chars": "Başvuran Karakterler",
        "card_approved_players": "Onaylanmış Oyuncular",
        "card_danger_zone": "Tehlikeli Bölge",
        "desc_danger_zone_camp": "Bu işlem geri alınamaz. Kampanyayı, içindeki tüm oyuncuları ve başvuruları kalıcı olarak siler.",
        "btn_delete_campaign": "Kampanyayı Kalıcı Olarak Sil",
        
        // --- Import / Export ---
        "card_char_data": "Karakter Verisi",
        "desc_char_data": "Karakterinizi bir .json dosyası olarak kaydedebilir veya daha önce kaydettiğiniz bir dosyayı yükleyebilirsiniz. Bu, karakterinizi paylaşmanın en iyi yoludur.",
        "desc_danger_zone_char": "Bu işlem geri alınamaz. Mevcut karakterinizdeki tüm verileri (aspektler, beceriler, stunt'lar) sıfırlar.",

        "msg_saved": "Kaydedildi!",
        
        // --- Placeholder (Silik Yazılar) ---
        "placeholder_stunt": "Yeni Stunt açıklaması...",
        "placeholder_char_desc": "Karakterinizin kısa tanımı...",
        "placeholder_camp_name": "Örn: 'Kayıp Kader Kristali'",
        "placeholder_camp_gm": "Görünmesini istediğiniz isim...",
        "placeholder_camp_setting": "Örn: 'Ev Yapımı Fantastik, Cyberpunk'",
        "placeholder_camp_desc": "Oyuncular için kısa bir macera kancası...",
        "placeholder_camp_lore": "Ev kuralları, önemli NPC'ler, dünya bilgisi...",
        "placeholder_camp_password": "Unutmayacağınız bir şifre girin",
        "placeholder_gm_aspect": "Yeni durum aspekti...",
        "placeholder_high_concept": "Örn: 'Sihir Güçlü Kılıç Ustası'",
        "placeholder_trouble": "Örn: 'Altına Olan Zafiyeti'",
        "placeholder_relationship": "Örn: 'Eski Ustama Borçluyum'",
        "placeholder_aspect": "Serbest aspektiniz...",
        
        "card_live_aspects": "Canlı Durum Aspektleri (GM)",

        // === MODAL MESAJLARI (EKSİKSİZ) ===
        "msg_error": "Hata",
        "msg_success": "Başarılı",
        "msg_warning": "Uyarı",
        "msg_confirmation": "Onay",
        "msg_operation_blocked": "İşlem Engellendi",
        "msg_connection_error": "Bağlantı Hatası",
        "msg_limit_exceeded": "Limit Aşıldı",
        "msg_rule_violation": "Kural İhlali",
        "msg_login_error": "Giriş Hatası",
        "msg_capacity_full": "Kapasite Dolu",
        
        "txt_blocked_live": "Bir kampanyaya bağlıyken bu işlemi yapamazsınız. Lütfen önce oyundan ayrılın.",
        "txt_last_char_warning": "Bu son karakteriniz. Son karakteri silemezsiniz. (Bunun yerine 'Karakteri Sıfırla' butonunu kullanın.)",
        "txt_delete_char_confirm": "{name} adlı karakteri kalıcı olarak silmek istediğinizden emin misiniz?",
        "txt_reset_char_confirm": "{name} adlı karakterin tüm verilerini sıfırlamak istediğinizden emin misiniz?",
        "txt_stunt_limit": "Stunt limitine ulaştınız. Refresh puanınızı düşürmelisiniz.",
        "txt_refresh_limit": "Refresh'i {value} değerine düşüremezsiniz. Önce Stunt silmelisiniz.",
        "txt_skill_pyramid": "Sadece {limit} adet '+{value}' beceriye sahip olabilirsiniz.",
        "txt_fate_point_limit": "Harcanacak Fate Puanın yok!",
        "txt_import_success": "Karakter başarıyla içe aktarıldı.",
        "txt_import_overwrite": "{new} karakterini yüklüyorsunuz.\n'Onayla': {current} üzerine yaz.\n'İptal': Yeni olarak ekle.",
        "txt_char_updated": "Karakter başarıyla güncellendi.",
        "txt_char_added": "Karakter başarıyla listeye eklendi.",
        "txt_invalid_file": "Geçersiz karakter dosyası.",
        "txt_leave_game_confirm": "Şu an bağlı olduğunuz oyundan ayrılmak istediğinize emin misiniz?",
        "txt_leave_success": "Oyundan başarıyla ayrıldınız.",
        "txt_gm_password_prompt": "Bu kampanyayı yönetmek için şifrenizi girin:",
        "txt_password_wrong": "Şifre yanlış!",
        "txt_campaign_created": "Kampanyanız lobiye eklendi.",
        "txt_campaign_updated": "Kampanya güncellendi.",
        "txt_missing_info": "Lütfen gerekli alanları doldurun.",
        "txt_delete_campaign_confirm": "Bu kampanyayı kalıcı olarak silmek istediğinizden emin misiniz?",
        "txt_delete_campaign_prompt": "Silmek için kampanya adını yazın: '{name}'",
        "txt_name_mismatch": "Girilen isim eşleşmedi.",
        "txt_campaign_deleted": "Kampanya silindi.",
        "txt_kick_confirm": "{name} adlı oyuncuyu oyundan atmak istediğinizden emin misiniz?",
        "txt_kicked": "{name} oyundan atıldı.",
        "txt_approve_confirm": "{name} adlı karakteri oyuna onaylamak istiyor musunuz?",
        "txt_approved": "{name} oyuna onaylandı!",
        "txt_deny_confirm": "{name} başvurusunu reddetmek istiyor musunuz?",
        "txt_submit_missing": "Lütfen İsim ve High Concept alanlarını doldurun.",
        "txt_submit_confirm": "{name} karakterini '{campaign}' oyununa göndermek istiyor musunuz?",
        "txt_submitted": "Başvuru alındı!",
        "txt_live_connection_lost": "Oyuna olan canlı bağlantı koptu.",
        "txt_application_status": "Başvurunuz reddedildi veya oyundan çıkarıldınız.",
        "txt_player_count_error": "Kişi sayısı 1-10 arasında olmalı.",
        "txt_firebase_error": "Veritabanı (Firebase) hatası oluştu.",
        
        // --- Durum Çubuğu Mesajları ---
        "txt_status_live": "CANLI MOD: \"{campaign}\" oyununa bağlısınız.",
        "txt_status_pending": "ONAY BEKLENİYOR: \"{campaign}\" oyunu için başvurunuz alındı.",
        // lang.js İÇİNDEKİ 'tr' BÖLÜMÜNE EKLE:
        "txt_fate_gt_refresh": "Fate Puanı, Refresh değerinden yüksek olamaz.",
        "label_limit": "Limit:",
        "label_used": "Kullanılan:",
        "txt_empty_stunt": "(Boş)",
        // TR Bölümü içine:
"lbl_fate_cost": "-1 Fate Puanı",
// TR Bölümü:
"txt_unnamed_char": "İsimsiz Karakter",
"txt_char_deleted_success": "Karakter başarıyla silindi.",
        "txt_char_reset_success": "Aktif karakter başarıyla sıfırlandı.",
    },
    
    en: {
        // --- Navigation ---
        "nav_char": "Character Sheet",
        "nav_roller": "Dice Roller",
        "nav_find_campaign": "Find Campaign",
        "nav_campaign": "Campaign Panel (GM)",
        "nav_tools": "Import / Export",
        "nav_gm_admin": "GM Admin",
        "nav_credits": "Credits",

        // --- Card Headers ---
        "card_char_info": "Character Info",
        "card_aspects": "Aspects",
        "card_skills": "Skills",
        "card_stunts": "Stunts",
        "card_stress": "Stress & Consequences",
        
        // --- Labels ---
        "label_name": "Name:",
        "label_desc": "Description:",
        "label_refresh": "Refresh:",
        "label_fate_points": "Fate Points:",
        "label_high_concept": "High Concept:",
        "label_trouble": "Trouble:",
        "label_relationship": "Relationship:",
        "label_aspect1": "Free Aspect 1:",
        "label_aspect2": "Free Aspect 2:",
        
        // --- Stress ---
        "header_phys_stress": "Physical Stress",
        "header_ment_stress": "Mental Stress",
        "header_consequences": "Consequences",
        "label_mild": "Mild (-2):",
        "label_mild_extra": "Extra Mild (-2):",
        "label_moderate": "Moderate (-4):",
        "label_severe": "Severe (-6):",

        // --- Roller ---
        "card_roller_title": "FATE DICE ROLLER",
        "card_roll_history": "Roll History",
        "btn_roll": "ROLL DICE",
        "label_roll_skill": "Skill:",
        "log_roll_dice": "Dice",
        "log_roll_skill": "Skill",
        "log_roll_total": "Total",
        "log_fate_spent": "Fate Point spent!",
        
        // --- Ladder ---
        "ladder_8": "Legendary!",
        "ladder_7": "Epic!",
        "ladder_6": "Fantastic!",
        "ladder_5": "Superb!",
        "ladder_4": "Great!",
        "ladder_3": "Good!",
        "ladder_2": "Fair!",
        "ladder_1": "Average",
        "ladder_0": "Mediocre",
        "ladder_-1": "Poor",
        "ladder_-2": "Terrible",
        "ladder_-3": "Abysmal!",
        "ladder_-4": "Catastrophic!",

        // --- Skills ---
        "skill_academics": "Academics",
        "skill_athletics": "Athletics",
        "skill_burglary": "Burglary",
        "skill_contacts": "Contacts",
        "skill_crafts": "Crafts",
        "skill_deceive": "Deceive",
        "skill_drive": "Drive",
        "skill_empathy": "Empathy",
        "skill_fight": "Fight",
        "skill_investigate": "Investigate",
        "skill_lore": "Lore",
        "skill_notice": "Notice",
        "skill_physique": "Physique",
        "skill_provoke": "Provoke",
        "skill_rapport": "Rapport",
        "skill_resources": "Resources",
        "skill_shoot": "Shoot",
        "skill_stealth": "Stealth",
        "skill_will": "Will",

        // --- Credits ---
        "credits_title": "Credits",
        "credits_dev": "Developer & Coding",
        "credits_design": "Design & Ideas",
        "credits_translation": "Translation Team",

        // --- General ---
        "btn_add": "Add",
        "btn_delete": "Delete",
        "btn_cancel": "Cancel",
        "btn_confirm": "Confirm",
        "btn_ok": "OK",
        "btn_close": "Close",
        "btn_submit_char": "Submit Character",
        "btn_manage": "Manage",
        "btn_update_campaign": "Update Campaign Info",
        "btn_create_campaign": "Create Campaign",
        "btn_export": "Export Character",
        "btn_import": "Import Character",
        "btn_reset": "Reset Character",
        "btn_leave_campaign": "Leave Campaign",
        "btn_add_result": "ADD +2 TO RESULT",
        "btn_reroll": "REROLL",
        
        // --- Status Buttons ---
        "btn_creating": "Creating...",
        "btn_updating": "Updating...",
        
        // --- Campaign ---
        "card_public_campaigns": "Public Campaigns",
        "desc_public_campaigns": "Search for existing games and submit your character. If you are a GM, click 'Manage' and enter your password.",
        "card_new_campaign": "Create New Campaign (GM)",
        "desc_new_campaign": "Fill in the information players will see in the lobby.",
        "label_camp_name": "Game Name:",
        "label_camp_gm": "GM Name:",
        "label_camp_system": "System:",
        "label_camp_setting": "Setting / World:",
        "label_camp_players": "Max Players:",
        "label_camp_desc": "Story Hook:",
        "label_camp_lore": "Details / Lore (Optional):",
        "label_camp_password": "Admin Password:",
        
        "card_gm_admin": "Campaign Management",
        "desc_gm_admin": "Only the campaign GM can see this page.",
        "card_situation_aspects": "Situation Aspects",
        "card_gm_fate": "GM Fate Points",
        "label_current_points": "Current Points:",
        "card_submitted_chars": "Submitted Characters",
        "card_approved_players": "Approved Players",
        "card_danger_zone": "Danger Zone",
        "desc_danger_zone_camp": "This action cannot be undone. Permanently deletes the campaign, all players, and submissions within it.",
        "btn_delete_campaign": "Permanently Delete Campaign",
        
        // --- Import / Export ---
        "card_char_data": "Character Data",
        "desc_char_data": "You can save your character as a .json file or load a previously saved file. This is the best way to share your character.",
        "desc_danger_zone_char": "This action cannot be undone. Resets all data (aspects, skills, stunts) in your current character.",

        "msg_saved": "Saved!",
        
        // --- Placeholders ---
        "placeholder_stunt": "New Stunt description...",
        "placeholder_char_desc": "Short description of your character...",
        "placeholder_camp_name": "e.g., 'The Lost Fate Crystal'",
        "placeholder_camp_gm": "Name you want to display...",
        "placeholder_camp_setting": "e.g., 'Homebrew Fantasy, Cyberpunk'",
        "placeholder_camp_desc": "A short adventure hook for players...",
        "placeholder_camp_lore": "House rules, important NPCs, world info...",
        "placeholder_camp_password": "Enter a password you won't forget",
        "placeholder_gm_aspect": "New situation aspect...",
        "placeholder_high_concept": "e.g., 'Wizard Private Eye'",
        "placeholder_trouble": "e.g., 'Sucker for a Pretty Face'",
        "placeholder_relationship": "e.g., 'I owe my old master'",
        "placeholder_aspect": "Your free aspect...",
        
        "card_live_aspects": "Live Situation Aspects (GM)",

        // === NEW: MODAL MESSAGES ===
        "msg_error": "Error",
        "msg_success": "Success",
        "msg_warning": "Warning",
        "msg_confirmation": "Confirmation",
        "msg_operation_blocked": "Operation Blocked",
        "msg_connection_error": "Connection Error",
        "msg_limit_exceeded": "Limit Exceeded",
        "msg_rule_violation": "Rule Violation",
        "msg_login_error": "Login Error",
        "msg_capacity_full": "Capacity Full",
        
        "txt_blocked_live": "You cannot perform this action while connected to a campaign. Please leave the game first.",
        "txt_last_char_warning": "This is your last character. You cannot delete the last character. (Use 'Reset Character' instead.)",
        "txt_delete_char_confirm": "Are you sure you want to permanently delete {name}?",
        "txt_reset_char_confirm": "Are you sure you want to reset all data for {name}?",
        "txt_stunt_limit": "Stunt limit reached. You must lower your Refresh.",
        "txt_refresh_limit": "You cannot lower Refresh to {value}. Delete stunts first.",
        "txt_skill_pyramid": "You can only have {limit} skill(s) at +{value}.",
        "txt_fate_point_limit": "You have no Fate Points to spend!",
        "txt_import_success": "Character imported successfully.",
        "txt_import_overwrite": "Loading {new}.\n'Confirm': Overwrite {current}.\n'Cancel': Add as new.",
        "txt_char_updated": "Character successfully updated.",
        "txt_char_added": "Character successfully added to list.",
        "txt_invalid_file": "Invalid character file.",
        "txt_leave_game_confirm": "Are you sure you want to leave the current game?",
        "txt_leave_success": "You have left the game.",
        "txt_gm_password_prompt": "Enter password to manage this campaign:",
        "txt_password_wrong": "Wrong password!",
        "txt_campaign_created": "Campaign added to the lobby.",
        "txt_campaign_updated": "Campaign updated.",
        "txt_missing_info": "Please fill in the required fields.",
        "txt_delete_campaign_confirm": "Are you sure you want to permanently delete this campaign?",
        "txt_delete_campaign_prompt": "Type campaign name to delete: '{name}'",
        "txt_name_mismatch": "Name mismatch.",
        "txt_campaign_deleted": "Campaign deleted.",
        "txt_kick_confirm": "Are you sure you want to kick {name}?",
        "txt_kicked": "{name} has been kicked.",
        "txt_approve_confirm": "Do you want to approve {name}?",
        "txt_approved": "{name} approved!",
        "txt_deny_confirm": "Do you want to deny the application for {name}?",
        "txt_submit_missing": "Please fill in Name and High Concept.",
        "txt_submit_confirm": "Do you want to submit {name} to '{campaign}'?",
        "txt_submitted": "Application submitted!",
        "txt_live_connection_lost": "Live connection to the game was lost.",
        "txt_application_status": "Your application was denied or you were kicked.",
        "txt_player_count_error": "Player count must be between 1 and 10.",
        "txt_firebase_error": "Database (Firebase) error occurred.",

        // --- Status Messages ---
        "txt_status_live": "LIVE MODE: Connected to \"{campaign}\".",
        "txt_status_pending": "APPROVAL PENDING: Application sent for \"{campaign}\".",
        // lang.js İÇİNDEKİ 'en' BÖLÜMÜNE EKLE:
        "txt_fate_gt_refresh": "Fate Points cannot exceed Refresh value.",
        "label_limit": "Limit:",
        "label_used": "Used:",
        "txt_empty_stunt": "(Empty)",
        // EN Bölümü içine:
"lbl_fate_cost": "-1 Fate Point",
// EN Bölümü:
"txt_unnamed_char": "Unnamed Character",
"txt_char_deleted_success": "Character deleted successfully.",
        "txt_char_reset_success": "Active character reset successfully.",
    }
};